# Konfiguracja agenta
frequency_minutes: 60  # jak często sprawdzać (domyślnie co 60 min)

# USTAWIENIA WEBSEARCH
websearch:
  engine: "google_cse"     # "bing" albo "google_cse" (Google Custom Search)
  region: "pl-PL"          # wpływa na język/wyniki regionalne
  max_results: 15          # ile linków przetwarzać na produkt
  site_whitelist:          # opcjonalnie: ["x-kom.pl","euro.com.pl","komputronik.pl"]
    - ".pl"
    - ".cz"
    - "amazon.de"
    - "amazon.eu"
  site_blacklist:          # opcjonalnie: ["aliexpress.com","olx.pl"]
    - "reddit.com"
    - "facebook.com"
    - "youtube.com"

# Filtrowanie dostępności (globalnie)
require_in_stock: true
availability_keywords:
  in_stock: []  # na razie puste; filtr działa wyłącznie przez "out_of_stock"
  out_of_stock:
    - "brak"
    - "niedostępny"
    - "chwilowo niedostępny"
    - "out of stock"
    - "preorder"
    - "na zamówienie"

# WALUTY
currency:
  parse_eur: true
  parse_czk: true
  eur_to_pln: 4.30   # tu wpisz kurs
  czk_to_pln: 0.18   # tu wpisz kurs (1 CZK ≈ 0.18 PLN)

products:
  - name: "Reolink E1 Outdoor SE PoE"   # fraza lub regex
    pattern: '(?i)\bReolink\b.*\bE1\b.*\bOutdoor\b.*\bSE\b.*\bPoE\b'   # Wzorzec regex (dopasuje różne warianty zapisu, bez rozróżniania wielkości liter)
    max_price_pln: 390
    stores: ["websearch"]

  - name: "Nowodvorski TAY 5293"   # fraza lub regex
    pattern: '(?i)^(?=.*\bnowodvorski\b)(?=.*\btay\b)(?=.*\b5293\b).*'   # Wzorzec regex (dopasuje różne warianty zapisu, bez rozróżniania wielkości liter)
    max_price_pln: 190
    stores: ["websearch"]


notifications:
  email:
    enabled: false
    smtp_host: "smtp.example.com"
    smtp_port: 587
    use_tls: true
    username: "user@example.com"
    password: "APP_PASSWORD"
    from_addr: "Price Watch <user@example.com>"
    to_addrs: ["user@example.com"]
  telegram:
    enabled: false
    bot_token: "123456:ABC-DEF..."  # utwórz bota @BotFather
    chat_id: "123456789"

# Ograniczenia grzecznościowe (rate limit itp.)
politeness:
  per_store_delay_seconds: 10
  request_timeout_seconds: 10
